name: Go
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true
      - name: Generate 'where' functions (for full linting immersion)
        run: go generate ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  go_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true
      - name: Generate 'where' functions
        run: go generate ./...
      - name: Test
        run: go test -v -count=1 ./...
